apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mkfd6l4to-python 
  janus-idp.io/tekton: mkfd6l4to-python
  backstage.io/kubernetes-id: mkfd6l4to-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mkfd6l4to-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  