apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: mkfd6l4to-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mkfd6l4to-python 
  name: mkfd6l4to-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: mkfd6l4to-python
    weight: 100 
