apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mkfd6l4to-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mkfd6l4to-python 
  name: mkfd6l4to-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mkfd6l4to-python 
